# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b8e72dd2e37c08c548f770ef5235ad4f6b202b9ed1c8bc8940d4edc6f94ba62103473fd464b220e68b0ade29d673eb4c67d8fb0fe33daf46a37ca7c5d59dc66

test:
  secret_key_base: 49af4f1c946116df5be937eca8cc7360bd25ea6fac5924760664a6a1d03dac1ad8e99eb48ba8f090dd5f5a7600f44bf26926cf98904c470d059e313cd307bbe1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
